version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/stamp
    binary: stamp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/stef16robbe/stamp/internal/cmd.Version={{.Version}}

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: stef16robbe
    name: stamp

brews:
  - name: stamp
    repository:
      owner: stef16robbe
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/stef16robbe/stamp"
    description: "A beautiful CLI for managing Architecture Decision Records (ADRs)"
    license: "MIT"
    install: |
      bin.install Dir.glob("stamp*").first => "stamp"
    test: |
      system "#{bin}/stamp", "version"
